## Exemples algebra ##

In [1]:
import numpy as np

### Vectors ###
arrays

In [2]:
v=np.array([1,0,0])
u=np.array([0,-2,0])

In [3]:
print(v,u)

[1 0 0] [ 0 -2  0]


Operacions amb vectors (suma, resta, producte escalar i vectorial)

In [7]:
w_s= u+v
w_r=u-v
print(w_s, w_r)

[ 1 -2  0] [-1 -2  0]


In [8]:
escalar = np.dot(u,v)
print(escalar)

0


In [9]:
vectorial = np.cross(u,v)
print(vectorial)

[0 0 2]


### Matrius ###

In [13]:
m_1=np.array([[2,4],[1,3]])
print(m_1)

[[2 4]
 [1 3]]


In [14]:
element = m_1[0,1]
print(element)

4


In [16]:
v_m= m_1[0,:]   # els : son un "comodin", li dic agafam tots els elements
print(v_m)

[2 4]


In [19]:
u_m= m_1[:,1] # accedeixo a la segona columna
print(u_m)

[4 3]


### Diagonalitzar, valors propis i vectors propis ###
per diagonalitzar han de ser cuadrades!
numpy treballa amb num complexos, pel que pot diagonalitzar qualsevol.

In [26]:
A=np.array([[2,2],[1,3]])

In [27]:
valors_propis,vectors_propis= np.linalg.eig(A)
print("Val propis", valors_propis)
print("Vec propis", vectors_propis)

Val propis [1. 4.]
Vec propis [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [31]:
Vp_1=vectors_propis[:,0]
Vp_2=vectors_propis[:,1]
print("Vp 1", Vp_1)
print("Vp 2", Vp_2)

Vp 1 [-0.89442719  0.4472136 ]
Vp 2 [-0.70710678 -0.70710678]


In [33]:
# Comprovacio que son vectors propis

z= np.dot(A,Vp_1)
print(z)

z_1= np.dot(A,Vp_2)
print(z_1)

[-0.89442719  0.4472136 ]
[-2.82842712 -2.82842712]


### Altres exemples de matrius ###

In [34]:
A=np.zeros([3,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
